import type { LucideIcon } from "lucide-react"
import {
  FileText,
  Hash,
  FileJson,
  ImageIcon,
  Palette,
  QrCode,
  Calculator,
  Clock,
  Code,
  Database,
  Key,
  Lock,
  FileCode,
  Sparkles,
  Zap,
  Globe,
} from "lucide-react"
import { CategoryId } from "@/constants/categories"

export type Tool = {
  name: string
  description: string
  icon: LucideIcon
  color: string
  href: string
  badge?: string
  category: CategoryId
}

export const tools: Tool[] = [
  {
    name: "JSON Formatter",
    description: "Format and validate JSON data",
    icon: FileJson,
    color: "bg-blue-500",
    badge: "Popular",
    href: "/json-formatter",
    category: CategoryId.Developer,
  },
  {
    name: "Image Compressor",
    description: "Compress images without losing quality",
    icon: ImageIcon,
    color: "bg-purple-500",
    badge: "New",
    href: "/image-compressor",
    category: CategoryId.Image,
  },
  {
    name: "QR Code Generator",
    description: "Generate QR codes for any text or URL",
    icon: QrCode,
    color: "bg-green-500",
    href: "/qr-generator",
    category: CategoryId.Converter,
  },
  {
    name: "Hash Generator",
    description: "Generate MD5, SHA1, SHA256 hashes",
    icon: Hash,
    color: "bg-orange-500",
    href: "/hash-generator",
    category: CategoryId.Security,
  },
  {
    name: "MD5 Generator",
    description: "Generate MD5 hash from text",
    icon: Hash,
    color: "bg-orange-600",
    badge: "Security",
    href: "/md5",
    category: CategoryId.Security,
  },
  {
    name: "Color Picker",
    description: "Pick colors and generate palettes",
    icon: Palette,
    color: "bg-pink-500",
    badge: "Popular",
    href: "/color-picker",
    category: CategoryId.Design,
  },
  {
    name: "Base64 Encoder",
    description: "Encode and decode Base64 strings",
    icon: Code,
    color: "bg-indigo-500",
    href: "/base64",
    category: CategoryId.Converter,
  },
  {
    name: "UUID Generator",
    description: "Generate unique identifiers",
    icon: Key,
    color: "bg-cyan-500",
    href: "/uuid-generator",
    category: CategoryId.Developer,
  },
  {
    name: "IP Lookup",
    description: "Get geolocation info for IP addresses",
    icon: Globe,
    color: "bg-blue-600",
    badge: "Network",
    href: "/ip-lookup",
    category: CategoryId.Network,
  },
  {
    name: "World Clock",
    description: "View time across different timezones",
    icon: Clock,
    color: "bg-amber-500",
    badge: "New",
    href: "/timezone",
    category: CategoryId.Converter,
  },
  {
    name: "Text Diff",
    description: "Compare two text files",
    icon: FileText,
    color: "bg-red-500",
    href: "/text-diff",
    category: CategoryId.Text,
  },
  {
    name: "Password Generator",
    description: "Generate strong secure passwords",
    icon: Lock,
    color: "bg-yellow-500",
    badge: "Popular",
    href: "/password-generator",
    category: CategoryId.Security,
  },
  {
    name: "Markdown Editor",
    description: "Write and preview Markdown",
    icon: FileCode,
    color: "bg-teal-500",
    href: "/markdown-editor",
    category: CategoryId.Text,
  },
  {
    name: "Unit Converter",
    description: "Convert between different units",
    icon: Calculator,
    color: "bg-lime-500",
    href: "/unit-converter",
    category: CategoryId.Converter,
  },
  {
    name: "SQL Formatter",
    description: "Format and beautify SQL queries",
    icon: Database,
    color: "bg-violet-500",
    href: "/sql-formatter",
    category: CategoryId.Developer,
  },
  {
    name: "Timestamp Converter",
    description: "Convert Unix timestamps",
    icon: Clock,
    color: "bg-amber-500",
    href: "/timestamp",
    category: CategoryId.Converter,
  },
  {
    name: "Text Case Converter",
    description: "Convert text to different cases",
    icon: Sparkles,
    color: "bg-rose-500",
    href: "/case-converter",
    category: CategoryId.Text,
  },
]
