import { CategoryId } from '@/constants/categories'
import type { LucideIcon } from 'lucide-react'
import {
  Binary,
  Calculator,
  Chrome,
  Code,
  CaseSensitive,
  Contrast,
  Eye,
  FileCode,
  FileJson,
  FileText,
  Gamepad2,
  Globe,
  Hash,
  ImageIcon,
  Key,
  Keyboard,
  Lock,
  MapPin,
  Palette,
  QrCode,
  ScanText,
  Shield,
  Calendar,
  Terminal,
  Link,
  ArrowRightLeft,
  Image,
  Activity,
  ShieldAlert,
} from 'lucide-react'

export type Tool = {
  name: string
  description: string
  icon: LucideIcon
  color: string
  href: string
  badge?: string
  category: CategoryId
}

export const tools: Tool[] = [
  {
    name: 'JSON Formatter',
    description: 'Format and validate JSON data',
    icon: FileJson,
    color: 'bg-blue-500',
    badge: 'Popular',
    href: '/json-formatter',
    category: CategoryId.Developer,
  },
  {
    name: 'JSON Viewer',
    description: 'View JSON in interactive tree format',
    icon: Eye,
    color: 'bg-cyan-500',
    badge: 'New',
    href: '/json-viewer',
    category: CategoryId.Developer,
  },
  {
    name: 'Data Converter',
    description: 'Convert between JSON, YAML, TOML, XML, Zod and CSV formats',
    icon: ArrowRightLeft,
    color: 'bg-emerald-500',
    badge: 'New',
    href: '/data-converter',
    category: CategoryId.Developer,
  },
  {
    name: 'Image Compressor',
    description: 'Compress images without losing quality',
    icon: ImageIcon,
    color: 'bg-purple-500',
    badge: 'New',
    href: '/image-compressor',
    category: CategoryId.Image,
  },
  {
    name: 'Text Extractor (OCR)',
    description: 'Extract text from images using OCR',
    icon: ScanText,
    color: 'bg-violet-500',
    badge: 'AI',
    href: '/text-extractor',
    category: CategoryId.Image,
  },
  {
    name: 'SVG Preview',
    description: 'Preview, edit, and export SVG files',
    icon: Image,
    color: 'bg-indigo-500',
    badge: 'New',
    href: '/svg-preview',
    category: CategoryId.Developer,
  },
  {
    name: 'QR Code Generator',
    description: 'Generate QR codes for any text or URL',
    icon: QrCode,
    color: 'bg-green-500',
    href: '/qr-generator',
    category: CategoryId.Utility,
  },
  {
    name: 'QR Code Parser',
    description: 'Extract text and URLs from QR code images',
    icon: QrCode,
    color: 'bg-emerald-500',
    badge: 'New',
    href: '/qr-parser',
    category: CategoryId.Utility,
  },
  {
    name: 'Hash Generator',
    description: 'Generate MD5, SHA1, SHA256 hashes',
    icon: Hash,
    color: 'bg-orange-500',
    href: '/hash-generator',
    category: CategoryId.Security,
  },
  {
    name: 'Color Picker',
    description: 'Pick colors and generate palettes',
    icon: Palette,
    color: 'bg-pink-500',
    badge: 'Popular',
    href: '/color-picker',
    category: CategoryId.Design,
  },
  {
    name: 'Color Contrast',
    description: 'Check WCAG AA/AAA contrast ratios',
    icon: Contrast,
    color: 'bg-emerald-500',
    href: '/color-contrast',
    category: CategoryId.Design,
  },
  {
    name: 'Base64 Encoder',
    description: 'Encode and decode Base64 strings',
    icon: Code,
    color: 'bg-indigo-500',
    href: '/base64',
    category: CategoryId.Developer,
  },
  {
    name: 'Variable Case Converter',
    description: 'Convert text into camelCase, snake_case, and more',
    icon: CaseSensitive,
    color: 'bg-fuchsia-600',
    badge: 'New',
    href: '/case-converter',
    category: CategoryId.Developer,
  },
  {
    name: 'Regular Expression Tester',
    description: 'Test and debug regex patterns with live matching',
    icon: FileCode,
    color: 'bg-purple-600',
    badge: 'New',
    href: '/regex-tester',
    category: CategoryId.Developer,
  },
  {
    name: 'Number Base Converter',
    description: 'Convert between binary, octal, decimal, hex',
    icon: Binary,
    color: 'bg-teal-600',
    badge: 'New',
    href: '/number-base',
    category: CategoryId.Developer,
  },
  {
    name: 'Chmod Generator',
    description: 'Generate chmod commands and understand file permissions',
    icon: Terminal,
    color: 'bg-orange-600',
    badge: 'New',
    href: '/chmod-generator',
    category: CategoryId.Developer,
  },
  {
    name: 'URL Parser/Generator',
    description: 'Parse URLs and build them from components',
    icon: Link,
    color: 'bg-sky-600',
    badge: 'New',
    href: '/url-parser',
    category: CategoryId.Developer,
  },
  {
    name: 'JWT Decoder',
    description: 'Decode and analyze JSON Web Tokens',
    icon: Shield,
    color: 'bg-violet-600',
    badge: 'New',
    href: '/jwt-decoder',
    category: CategoryId.Security,
  },
  {
    name: 'UUID Generator',
    description: 'Generate unique identifiers',
    icon: Key,
    color: 'bg-cyan-500',
    href: '/uuid-generator',
    category: CategoryId.Security,
  },
  {
    name: 'IP Lookup',
    description: 'Get geolocation info for IP addresses',
    icon: Globe,
    color: 'bg-blue-600',
    badge: 'Network',
    href: '/ip-lookup',
    category: CategoryId.Utility,
  },
  {
    name: 'User Agent Detector',
    description: 'Detect and analyze browser user agent',
    icon: Chrome,
    color: 'bg-cyan-600',
    badge: 'New',
    href: '/user-agent',
    category: CategoryId.Developer,
  },
  {
    name: 'HTTP Status Code',
    description: 'Reference guide for HTTP status codes',
    icon: Activity,
    color: 'bg-violet-500',
    badge: 'Reference',
    href: '/http-status-code',
    category: CategoryId.Developer,
  },
  {
    name: 'Will it CORS?',
    description: 'Analyze CORS issues and get solutions',
    icon: ShieldAlert,
    color: 'bg-rose-600',
    badge: 'New',
    href: '/will-it-cors',
    category: CategoryId.Security,
  },
  // {
  //   name: "World Clock",
  //   description: "View time across different timezones",
  //   icon: Clock,
  //   color: "bg-amber-500",
  //   badge: "New",
  //   href: "/timezone",
  //   category: CategoryId.Education,
  // },
  {
    name: 'Password Generator',
    description: 'Generate strong secure passwords',
    icon: Lock,
    color: 'bg-yellow-500',
    badge: 'Popular',
    href: '/password-generator',
    category: CategoryId.Security,
  },
  // {
  //   name: "Timestamp Converter",
  //   description: "Convert Unix timestamps",
  //   icon: Clock,
  //   color: "bg-amber-500",
  //   href: "/timestamp",
  //   category: CategoryId.Education,
  // },
  {
    name: 'Math Quiz Generator',
    description: 'Generate custom math practice quizzes',
    icon: Calculator,
    color: 'bg-blue-600',
    badge: 'New',
    href: '/math-quiz',
    category: CategoryId.Education,
  },
  {
    name: 'Typing Exercise',
    description: 'Practice and improve typing speed',
    icon: Keyboard,
    color: 'bg-teal-500',
    badge: 'Practice',
    href: '/typing-exercise',
    category: CategoryId.Education,
  },
  {
    name: 'Snake Game',
    description: 'Classic snake game - eat and grow!',
    icon: Gamepad2,
    color: 'bg-green-600',
    badge: 'Game',
    href: '/snake-game',
    category: CategoryId.Game,
  },
  {
    name: 'Country/Region Code Lookup',
    description: 'Search ISO country/region codes and info',
    icon: MapPin,
    color: 'bg-indigo-500',
    badge: 'Reference',
    href: '/country-region-code',
    category: CategoryId.Utility,
  },
  {
    name: 'Word Counter',
    description: 'Count words, characters, and analyze text',
    icon: FileText,
    color: 'bg-slate-500',
    badge: 'New',
    href: '/word-count',
    category: CategoryId.Utility,
  },
  {
    name: 'Public Holidays',
    description: 'Get public holidays for countries and regions',
    icon: Calendar,
    color: 'bg-rose-500',
    badge: 'New',
    href: '/public-holidays',
    category: CategoryId.Utility,
  },
]
